# Generated by Django 5.2.12 on 2026-03-30 17:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0004_book_uploaded_by_alter_book_content_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('is_active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reading.question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='ReadingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField(verbose_name='Начальная страница')),
                ('end_page', models.PositiveIntegerField(blank=True, null=True, verbose_name='Конечная страница')),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время начала')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('abandoned', 'Брошена')], default='active', max_length=20, verbose_name='Статус')),
                ('pages_read', models.PositiveIntegerField(default=0, verbose_name='Прочитано страниц в сессии')),
                ('is_daily_goal_completed', models.BooleanField(default=False, verbose_name='Дневная цель выполнена')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Сессия чтения',
                'verbose_name_plural': 'Сессии чтения',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_page', models.PositiveIntegerField(default=1, verbose_name='Начальная страница теста')),
                ('end_page', models.PositiveIntegerField(default=10, verbose_name='Конечная страница теста')),
                ('status', models.CharField(choices=[('pending', 'Ожидает прохождения'), ('passed', 'Пройден'), ('failed', 'Не пройден')], default='pending', max_length=20, verbose_name='Статус теста')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время создания')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Время прохождения')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='Количество правильных ответов')),
                ('total_questions', models.PositiveIntegerField(default=3, verbose_name='Всего вопросов')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='reading.readingsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reading.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='UserReadingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущий стрик')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Самый длинный стрик')),
                ('last_read_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего чтения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стрик чтения',
                'verbose_name_plural': 'Стрики чтения',
            },
        ),
        migrations.CreateModel(
            name='PageReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField(verbose_name='Номер страницы')),
                ('time_spent', models.DurationField(verbose_name='Время чтения страницы')),
                ('words_count', models.PositiveIntegerField(default=0, verbose_name='Количество слов на странице')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время завершения страницы')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_logs', to='reading.readingsession', verbose_name='Сессия')),
            ],
            options={
                'verbose_name': 'Лог чтения страницы',
                'verbose_name_plural': 'Логи чтения страниц',
                'unique_together': {('session', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.achievement', verbose_name='Достижение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Достижение пользователя',
                'verbose_name_plural': 'Достижения пользователей',
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.PositiveIntegerField(default=0, verbose_name='Правильные ответы')),
                ('total_questions', models.PositiveIntegerField(default=3, verbose_name='Всего вопросов')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время прохождения')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book', verbose_name='Книга')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reading.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_results', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Результат теста пользователя',
                'verbose_name_plural': 'Результаты тестов пользователей',
                'unique_together': {('user', 'book', 'test')},
            },
        ),
    ]
