# Generated by Django 5.2.12 on 2026-03-27 14:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_uploaded_by_alter_book_content_and_more'),
        ('reading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagereadinglog',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Время завершения страницы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingsession',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Последняя активность'),
        ),
        migrations.AddField(
            model_name='readingsession',
            name='pages_read',
            field=models.PositiveIntegerField(default=0, verbose_name='Прочитано страниц в сессии'),
        ),
        migrations.AlterField(
            model_name='pagereadinglog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_logs', to='reading.readingsession', verbose_name='Сессия'),
        ),
        migrations.AlterField(
            model_name='pagereadinglog',
            name='time_spent',
            field=models.DurationField(verbose_name='Время чтения страницы'),
        ),
        migrations.AlterField(
            model_name='pagereadinglog',
            name='words_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество слов на странице'),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_sessions', to='books.book', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='end_page',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Конечная страница'),
        ),
        migrations.AlterField(
            model_name='readingsession',
            name='status',
            field=models.CharField(choices=[('active', 'Активна'), ('completed', 'Завершена'), ('abandoned', 'Брошена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='UserReadingStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, verbose_name='Текущий стрик')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='Самый длинный стрик')),
                ('last_read_date', models.DateField(blank=True, null=True, verbose_name='Дата последнего чтения')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_streak', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Стрик чтения',
                'verbose_name_plural': 'Стрики чтения',
            },
        ),
    ]
