# Generated by Django 5.2.12 on 2026-03-09 20:17

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('is_account_active', models.BooleanField(default=False, help_text='Меняется с 0 на 1 при подтверждении email', verbose_name='Аккаунт активен')),
                ('is_superuser', models.BooleanField(default=False, help_text='Принадлежность к администраторам', verbose_name='Является суперюзером')),
                ('subscription_type', models.CharField(choices=[('active', 'Активна (10 книг)'), ('inactive', 'Не активна (1 книга)')], default='inactive', help_text='Лимит загружаемых книг: 10 при активной, 1 при неактивной', max_length=20, verbose_name='Тип подписки')),
                ('is_staff', models.BooleanField(default=False, help_text='Определяет, может ли пользователь войти в админку', verbose_name='Статус персонала')),
                ('is_active', models.BooleanField(default=True, help_text='Деактивирует аккаунт вместо удаления', verbose_name='Аккаунт активен')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
