# Generated by Django 5.2.12 on 2026-03-09 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('pages_count', models.PositiveIntegerField(verbose_name='Количество страниц')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('completed', 'Закончена'), ('deleted', 'Удалена')], default='in_progress', max_length=20, verbose_name='Статус')),
                ('daily_goal', models.PositiveIntegerField(default=5, verbose_name='Дневная цель')),
                ('content', models.BinaryField(verbose_name='Содержимое')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='UserConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('friendship', 'Дружба'), ('parent_child', 'Родитель_ребенок')], max_length=20, verbose_name='Тип')),
                ('is_parent_flag', models.BooleanField(default=False, verbose_name='Флаг родителя')),
                ('is_child_flag', models.BooleanField(default=False, verbose_name='Флаг дочерний')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь пользователей',
                'verbose_name_plural': 'Связи пользователей',
                'unique_together': {('user1', 'user2', 'connection_type')},
            },
        ),
    ]
