# Generated by Django 5.2.12 on 2026-03-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconnection',
            name='connection_type',
            field=models.CharField(choices=[('friendship', 'Дружба'), ('parent_child', 'Родитель_ребенок'), ('child_request', 'Запрос_от_ребенка'), ('pending', 'Ожидает_подтверждения')], max_length=20, verbose_name='Тип'),
        ),
    ]
