# Generated by Django 5.2.12 on 2026-03-24 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_userconnection_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='content',
            field=models.BinaryField(null=True, verbose_name='Содержимое'),
        ),
    ]
