# Generated by Django 6.0.3 on 2026-04-13 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_format_extracted_text'),
        ('books', '0004_book_uploaded_by_alter_book_content_and_more'),
    ]

    operations = [
    ]
